[package]
name = "rustneatsnake"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.7.1"
rand = "0.9.0"
rand_distr = "0.5.1"
raylib = "5.0.2"
rayon = "1.10.0"
strum = "0.27.1"
strum_macros = "0.27.1"
